FROM python:3.6.3-alpine3.6

COPY . .

RUN apk update ; apk add curl gcc libxml2 libxslt 	libxslt-dev libxml2-dev  musl-dev freetype-dev libjpeg-turbo-dev libpng-dev ; pip install -r ./requirements.txt ; curl https://raw.githubusercontent.com/codelucas/newspaper/master/download_corpora.py | python3
RUN pip install -r requirements.txt


CMD ["pytest", "tests"]
