version: "3.6"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.2.0
    container_name: anieko_elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      transport.host: "0.0.0.0"
      http.host: "0.0.0.0"
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      cluster.name: "aineko_elastic"
      network.host: "0.0.0.0"
      discovery.zen.minimum_master_nodes: "1"
      discovery.type: "single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - aineko_network
  kibana:
      depends_on:
        - elasticsearch
      image: docker.elastic.co/kibana/kibana-oss:7.2.0
      container_name: aineko_kibana
      environment:
        SERVER_NAME: kibananananana
        ELASTICSEARCH_URL: http://elasticsearch:9200
      ports:
        - "5601:5601"
      networks:
        - aineko_network
  aineko:
   depends_on:
     - elasticsearch
   build: .
   environment:
     ELASTICSEARCH_URL: elasticsearch:9200 # Omit http:// and port
     REDIS_URL: redis://redis
   networks:
     - aineko_network
  redis:
    image: redis:5.0.5
    container_name: redis
    volumes:
      - /home/modulus/data/redis:/data
    ports:
      - "6379:6379" 
    networks:
      - aineko_network
 # postgres:
 #   image: postgres:9.4-alpine
 #   container_name: aineko_postgres
 #   networks:
 #     - aineko_network
 #   environment:
 #     POSTGRES_PASSWORD: neverever
 #   ports:
 #     - "5432:5432"
networks:
  aineko_network:
    driver: bridge
