version: "3.3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    container_name: anieko_elasticsearch
   # volumes:
    #  - docker/elastic/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      transport.host: "0.0.0.0"
      http.host: "0.0.0.0"
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      cluster.name: "aineko_elastic"
      network.host: "0.0.0.0"
      discovery.zen.minimum_master_nodes: "1"
      discovery.type: "single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - aineko_network
  kibana:
      depends_on:
        - elasticsearch
      image: docker.elastic.co/kibana/kibana-oss:6.3.0
      container_name: aineko_kibana
      environment:
        SERVER_NAME: kibananananana
        ELASTICSEARCH_URL: http://elasticsearch:9200

      ports:
        - "5601:5601"
      environment:
        server.name: kibana
        server.host: "0"
        elasticsearch.url: http://elasticsearch:9200
      networks:
        - aineko_network
  aineko:
    depends_on:
      - elasticsearch
    build: .
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
  #redis:
  #  image: redis:3.2.11
  #  container_name: aineko_redis
   # networks:
   #   - aineko_network

#    cassandra:
#    image: cassandra:3.11.1
##    ports:
##      - "5556:7000"
#    networks:
#      - aineko_network
#    labels:
#      role: "Database"
#      type: "Cassandra"
#      tech: "NoSQL"
#    container_name: aineko_cassandra
#    environment:
#      CASSANDRA_LISTEN_ADDRESS: "192.168.1.4"
#      CASSANDRA_BROADCAST_ADDRESS: "192.168.1.4"

networks:
  aineko_network:
    driver: bridge
