---
  tags:
    - war
    - explosion
    - ai
    - artificial intelligence
    - stocks
    - stockmarket
    - stock
    - microsoft
    - apple
    - cpu
    - nvidia
    - amd
    - tech
    - technology
